### ISSUE TITLE
错误识别后无法再正常打开应用程序

### ISSUE THREAD

**Issue by 99Mr-Z** [nuthx/bangumi-autorenamer#16]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
  File "src\core.py", line 33, in __init__
  File "src\module\config.py", line 98, in oldConfigCheck
  File "src\module\config.py", line 125, in readConfig
  File "configparser.py", line 699, in read
  File "configparser.py", line 1022, in _read
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 81: illegal multibyte sequence

![image](https://github.com/nuthx/bangumi-renamer/assets/117721493/f54dcbd5-3007-425e-a0f9-96c9874e3ed6)

**Comment by nuthx** [comment]
打开配置文件目录 `C:\Users\outmo\AppData\Roaming\BangumiRenamer`，删除 `config.ini` 再重启软件
顺便贴一下 `config.ini` 的内容，我康康是咋回事

**Comment by 99Mr-Z** [comment]
[Application]
version = 2.0

[Format]
rename_format = {cn_name} {release}——{jp_name}
date_format = YYYY

[Bangumi]
user_id = 

[Counter]
open_times = 3
analysis_times = 13
rename_times = 0



> 打开配置文件目录 `C:\Users\outmo\AppData\Roaming\BangumiRenamer`，删除 `config.ini` 再重启软件 顺便贴一下 `config.ini` 的内容，我康康是咋回事
