### ISSUE TITLE
win10，打不开QAQ

### ISSUE THREAD

**Issue by Hyphen-H** [nuthx/bangumi-autorenamer#8]
![image](https://github.com/nuthx/bangumi-renamer/assets/103420806/e6566be0-fa54-4b8b-a982-eaa3d2d2e4c0)
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\core.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\gui\dialog.py", line 2, in <module>
ImportError: cannot import name 'MessageBoxBase' from 'qfluentwidgets' (C:\Users\ADMINI~1\AppData\Local\Temp\_MEI14242\qfluentwidgets\__init__.pyc)

**Comment by nuthx** [comment]
好像是编译时候包版本出问题了，晚上我细看一下
